<?php
/**
 * @file
 * Sepulsa UOB webform campaign.
 * @author  azul@sepulsa.com
 */

/**
 * Implements hook_menu().
 */
function sepulsa_uob_campaign_menu() {
  $items['admin/config/system/uob_submission_report'] = array(
    'title' => 'UOB Submission Report',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('sepulsa_uob_campaign_form'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Admin form to configure uob_submission_report.
 */
function sepulsa_uob_campaign_form($form, &$form_state) {
  $form['uob_mail_to'] = array(
    '#type' => 'textfield',
    '#title' => t('UOB Send Report To'),
    '#required' => TRUE,
    '#default_value' => variable_get('uob_mail_to', 'azul@sepulsa.com'),
  );
  $form['uob_mail_from'] = array(
    '#type' => 'textfield',
    '#title' => t('UOB Send From'),
    '#required' => TRUE,
    '#default_value' => variable_get('uob_mail_from', 'ken@sepulsa.com'),
  );
  $form['name']['uob_autosend'] = array(
    '#type' =>'checkbox',
    '#title'=>t('Autosend Submission'),
    '#default_value' => variable_get('uob_autosend',FALSE),
  );

  return system_settings_form($form);
}

function sepulsa_uob_campaign_form_webform_client_form_alter(&$form, &$form_state){
  if($form['#node']->title=='UOB'){
    $form['#validate'][] = 'sepulsa_uob_campaign_validation';
  }
}

function sepulsa_uob_campaign_validation(&$form, &$form_state)
{
  global $user;
  // $pattern_no_hp = '/^(\+62|0)[1-9]{9,11}$/';
  $pattern_no_hp = '^08[0-9]{9,}$';

  $telkomsel = "^(\\+62|\\+0|0|62)8(1[123]|52|53|21|22|23)[0-9]{5,9}$";
  $simpati = "^(\\+62|\\+0|0|62)8(1[123]|2[12])[0-9]{5,9}$";
  $as = "^(\\+62|\\+0|0|62)8(52|53|23)[0-9]{5,9}$";
  $indosat = "^(\\+62815|0815|62815|\\+0815|\\+62816|0816|62816|\\+0816|\\+62858|0858|62858|\\+0814|\\+62814|0814|62814|\\+0814)[0-9]{5,9}$";
  $im3  = "^(\\+62855|0855|62855|\\+0855|\\+62856|0856|62856|\\+0856|\\+62857|0857|62857|\\+0857)[0-9]{5,9}$";
  $xl = "^(\\+62817|0817|62817|\\+0817|\\+62818|0818|62818|\\+0818|\\+62819|0819|62819|\\+0819|\\+62859|0859|62859|\\+0859|\\+0878|\\+62878|0878|62878|\\+0877|\\+62877|0877|62877)[0-9]{5,9}$";


  $term_agree = (isset($form_state['input']['submitted']['term_agree']['agree'])==null) ? FALSE : TRUE;
  $no_hp = $form_state['input']['submitted']['no_hp'];
  $nama_lengkap = $form_state['input']['submitted']['nama_lengkap'];
  $kode_pos = $form_state['input']['submitted']['kode_pos'];
  $kota = $form_state['input']['submitted']['kota'];
  $no_ktp = $form_state['input']['submitted']['no_ktp'];
  $alamat_email = $form_state['input']['submitted']['alamat_email'];
  $jenis_kelamin = $form_state['input']['submitted']['jenis_kelamin'];
  $day_lahir = $form_state['input']['submitted']['tanggal_lahir']['day'];
  $month_lahir = $form_state['input']['submitted']['tanggal_lahir']['month'];
  $year_lahir = $form_state['input']['submitted']['tanggal_lahir']['year'];

  if($user->uid==0){
    form_set_error('', t('Silahkan login terlebih dahulu.'));
  }

  if (empty($nama_lengkap)) {
    form_set_error('nama_lengkap', t('Nama lengkap harus diisi'));
  }
  if (empty($no_hp) && !preg_match($pattern_no_hp, $no_hp)) {
    form_set_error('no_hp', t('No HP harus angka yang diawali 08 minimal 11 digit'));
  }
  if (empty($kode_pos)) {
    form_set_error('kode_pos', t('Kode pos harus diisi'));
  }
  if (empty($kota)) {
    form_set_error('kota', t('Kota harus diisi'));
  }

  if (empty($alamat_email) && !valid_email_address($alamat_email) ) {
    form_set_error('alamat_email', t('Alamat email harus diisi'));
  }
  if (empty($jenis_kelamin)) {
    form_set_error('jenis_kelamin', t('Pilih jenis kelamin'));
  }
  if (empty($day_lahir) || empty($month_lahir) || empty($year_lahir) ) {
    form_set_error('tanggal_lahir', t('Tanggal lahir harus diisi'));
  }
  if (empty($no_ktp)) {
    form_set_error('no_ktp', t('No KTP harus diisi'));
  }
  if (empty($term_agree)) {
    form_set_error('term_agree agree', t('Terms & Conditions harus disetujui'));
  }

}


function sepulsa_uob_campaign_preprocess_page(&$vars, $hook) {

  $destination = $vars['node']->title;
  if($destination=='UOB'){
    $anonym = false;
    if(!empty(user_is_anonymous())) {
      $anonym = true;
    }
    $uobvars = [
      'destination' => $destination,
      'anonym' => $anonym,
      'forgot_destination' => '/user/password?destination='.$destination,
      'register_destination' => '/user/register?destination='.$destination,
    ];

    drupal_add_js(array('sepulsa_uob_campaign' => array('uobvars' => $uobvars)),
      array('type' => 'setting', 'scope' => 'header', 'weight' => 115));

    drupal_add_js(drupal_get_path('module', 'sepulsa_uob_campaign') . '/uob.js');
    }
  }
