<?php

  function sepulsa_s3fs_form_alter(&$form, &$form_state, $form_id)
  {
    //drupal_set_message($form_id);
    if($form_id == 's3fs_actions')
    {
      $form['s3fs_copy_themes'] = array(
        '#type' => 'fieldset',
        '#description' => t(
          "Since you have S3 File System configured to take over for the local themes files, you
          may wish to copy any files which were previously uploaded to your site into your S3 bucket. <br>
          If you have a lot of files, or very large files, you'll want to use <i>drush s3fs-copy-local</i>
          instead of this form, as the limitations imposed by browsers may break very long copy operations."
        ),
        '#title' => t('Copy Local Themes Files to S3'),
      );
      $form['s3fs_copy_themes']['sepulsa'] = array(
          '#type' => 'submit',
          '#prefix' => '<br>',
          '#name' => 'sepulsa',
          '#value' => t('Copy local themes files to S3'),
          '#submit' => array('_s3fs_copy_themes_submit'),
      );
    }
  }

  function _s3fs_copy_themes_submit($form, &$form_state) {
    _s3fs_copy_file_themes_to_s3($form_state['triggering_element']['#name']);
  }

  function _s3fs_copy_file_themes_to_s3() {
    $source_folder = realpath(variable_get('', 'sites/all/themes'));
    $target_folder = !empty($config['public_folder']) ? $config['public_folder'] . '/' : 's3fs-public/';

    if (!empty($config['root_folder'])) {
      $target_folder = "{$config['root_folder']}/$target_folder";
    }

    $file_paths = _s3fs_themes_recursive_dir_scan($source_folder);
    foreach ($file_paths as $path) {
      $relative_path = str_replace($source_folder . '/', '', $path);

      // print "Copying public://$relative_path into S3...\n";
      // // Finally get to make use of S3fsStreamWrapper's "S3 is actually a local
      // // file system. No really!" functionality.
      if(preg_match('#\.(css|js|png|jpeg|jpg|svg|gif|ico)$#', $relative_path))
      {
        copy($path, "public://sites/all/themes/$relative_path");
      }
    }
    drupal_set_message(t('Copied all local themes files to S3.', array('%scheme' => 'public')), 'status');
  }

  function _s3fs_themes_recursive_dir_scan($dir) {
    $output = array();
    $files = scandir($dir);
    foreach ($files as $file) {
      $path = "$dir/$file";

       if ($file != '.' && $file != '..') {
         // In case they put their private root folder inside their public one,
         // skip it. When listing the private file system contents, $path will
         // never trigger this.
         if ($path == realpath(variable_get('file_private_path'))) {
           continue;
         }

        if (is_dir($path)) {
           $output = array_merge($output, _s3fs_themes_recursive_dir_scan($path));
         }
         else {
           $output[] = $path;
         }
      }
    }
    // echo "<pre>";
    // print_r($output);die;
    return $output;
  }
?>
