<?php
/**
 * @file
 * Sepulsa Buy Now Button module.
 */

/**
 * Implements hook_block_info().
 */
function sepulsa_buy_now_button_block_info() {
  $blocks = array();
  $blocks['sepulsa_buy_now_button'] = array(
    'info' => t('Sepulsa Buy Now Button'),
  );
  return $blocks;
}

/**
 * Implements hook_block_configure().
 */
function sepulsa_buy_now_button_block_configure($delta = '') {
  $form = array();
  switch ($delta) {
    case 'sepulsa_buy_now_button':
      // UTM Source.
      $form['sepulsa_buy_now_button_utm_source'] = array(
        '#type' => 'textfield',
        '#title' => t('UTM Source'),
        '#default_value' => variable_get('sepulsa_buy_now_button_utm_source', ''),
      );
      // UTM Medium.
      $form['sepulsa_buy_now_button_utm_medium'] = array(
        '#type' => 'textfield',
        '#title' => t('UTM Medium'),
        '#default_value' => variable_get('sepulsa_buy_now_button_utm_medium', ''),
      );
      // UTM Campaign.
      $form['sepulsa_buy_now_button_utm_campaign'] = array(
        '#type' => 'textfield',
        '#title' => t('UTM Campaign'),
        '#default_value' => variable_get('sepulsa_buy_now_button_utm_campaign', ''),
      );
      break;
  }
  return $form;
}

/**
 * Implements hook_block_save().
 */
function sepulsa_buy_now_button_block_save($delta = '', $edit = array()) {
  switch ($delta) {
    case 'sepulsa_buy_now_button':
      variable_set('sepulsa_buy_now_button_utm_source', $edit['sepulsa_buy_now_button_utm_source']);
      variable_set('sepulsa_buy_now_button_utm_medium', $edit['sepulsa_buy_now_button_utm_medium']);
      variable_set('sepulsa_buy_now_button_utm_campaign', $edit['sepulsa_buy_now_button_utm_campaign']);
      break;
  }
}

/**
 * Implements hook_block_view().
 */
function sepulsa_buy_now_button_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'sepulsa_buy_now_button':
      $data['sepulsa_buy_now_button_utm_source'] = variable_get('sepulsa_buy_now_button_utm_source');
      $data['sepulsa_buy_now_button_utm_medium'] = variable_get('sepulsa_buy_now_button_utm_medium');
      $data['sepulsa_buy_now_button_utm_campaign'] = variable_get('sepulsa_buy_now_button_utm_campaign');
      $block['content'] = theme('sepulsa_buy_now_button', array('data' => $data));
      break;
  }

  return $block;
}

/**
 * Implements hook_theme().
 */
function sepulsa_buy_now_button_theme() {
  return array(
    'sepulsa_buy_now_button' => array(
      'variables' => array('data' => NULL),
      'template' => 'sepulsa-buy-now-button',
    ),
  );
}
