<?php
/**
 * @file
 * UOB webform report.
 */

/**
 * Implements hook_menu().
 */
function uob_webform_report_menu() {
  $items['admin/config/system/uob_submission_report'] = array(
    'title' => 'UOB Submission Report',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('uob_webform_report_form'),
    'access arguments' => array('administer'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Admin form to configure uob_submission_report.
 */
function uob_webform_report_form($form, &$form_state) {
  $form['uob_mail_to'] = array(
    '#type' => 'textfield',
    '#title' => t('UOB Send Report To'),
    '#required' => TRUE,
    '#default_value' => variable_get('uob_mail_to', 'sibirudroid@yahoo.com'),
  );
  $form['uob_mail_from'] = array(
    '#type' => 'textfield',
    '#title' => t('UOB Send From'),
    '#required' => TRUE,
    '#default_value' => variable_get('uob_mail_from', 'ken@sepulsa.com'),
  );

  return system_settings_form($form);
}

/**
 * Implements hook_cron().
 */
function uob_webform_report_cron() {
  // Generate UOB webform submission result into a file.
  $current_date = date('d-m-Y H:i');
  $filepath='public://';
  $filename = 'UOB_submission_report.xls';
  $view = views_get_view('uob_submission');
  $display = $view->preview('views_data_export_1');
  if($display){
    $file_saved=file_unmanaged_save_data($display , $filepath.$filename, FILE_EXISTS_REPLACE);
  }else{
    watchdog('uob_webform_report',
      'Views export data for UOB webform is empty!',
      array(),
      WATCHDOG_INFO
    );
  }
  if(!empty($file_saved)){
    // Log the file
    watchdog('uob_webform_report',
      'Generate UOB webform submisssion : @current_date  The file : <pre>@files</pre> ',
      array(
        '@current_date' => $current_date,
        '@files' => print_r($filepath.$filename, TRUE),
      ),
      WATCHDOG_INFO
    );
    // Send email with attachment file to configured email.
    // Where $filepathname should contain the path to the file and,
    // and $filename should contain the name of the file.
    $attachment = array(
      'filecontent' => file_get_contents($filepath.$filename),
      'filename' => $filename,
      'filemime' => 'application/vnd.ms-excel',
    );

    $download_link = file_create_url($filepath.$filename);

    // Mail to & from.
    $to = variable_get('uob_mail_to', 'sibirudroid@yahoo.com');
    $from = variable_get('uob_mail_from', 'ken@sepulsa.com');

    $params = array(
      'headers' => array('Content-Type' => 'text/html'),
      'key' => 'test',
      'subject' => 'UOB Campaign submission report: ' . $current_date,
      'body' => 'Below is download link UOB Campaign submission report: ' . $current_date. ' <br>' . $download_link,
      'attachment' => $attachment,
    );

    $send = drupal_mail('uob_webform_report', 'uob_webform_send_report', $to, language_default(), $params, $from, $send = TRUE);
    if($send){
      watchdog('uob_webform_report',
        'Send email to: ' . $to . ' with file: '.$filename,
        array(
          '@to' => $to,
          '@files' => print_r($filepath.$filename, TRUE),
        ),
        WATCHDOG_INFO
      );
    }
  } // End file saved check
}

/**
 * Implements hook_mail().
 */
function uob_webform_report_mail($key, &$message, $params) {
  $message['subject'] = $params['subject'];
  $message['body'][] = $params['body'];

  // Add attachment when available.
  if (isset($params['attachment'])) {
    $message['params']['attachments'][] = $params['attachment'];
  }
}
