<?php

/**
 * Implements hook_commerce_checkout_pane_info().
 */
function userpoints_sepulsa_commerce_checkout_pane_info() {
  $checkout_panes = array();
  $checkout_panes['userpoints_sepulsa'] = array(
    'title' => t('Userpoint Sepulsa'),
    'page' => 'checkout',
    'file' => 'userpoints_sepulsa.checkout_pane.inc',
    'base' => 'userpoints_sepulsa_pane',
    'weight' => 10,
  );

  return $checkout_panes;
}

/**
 * Implements hook_theme().
 */
function userpoints_sepulsa_theme($existing, $type, $theme, $path) {
    return array(
      'userpoints_list_transaction' => array(
        'variables' => array('content' => NULL),
        'template' => 'userpoints_list_transaction', // place you file in 'theme' folder of you module folder
        'path' => drupal_get_path('module', 'userpoints_sepulsa')
      )
    );
}
    
// Override Point Tab from Userpoints Module
function userpoints_sepulsa_menu_alter(&$items) {
    unset($items['user/%user/points']);
    
    $items['user/%user/points'] = array(
        'title' => 'Sepulsa Kredit',
        'title arguments' => userpoints_translation(),
        'page callback' => 'userpoints_list_transaction',
        'page arguments' => array('userpoints_list_transactions', 1),
        'access callback' => 'userpoints_access_my_points',
        'access arguments' => array(1),
        'type' => MENU_LOCAL_TASK,
        'weight' => 1,
    );
}

function userpoints_list_transaction(){
    $rows = [];
    global $user;
    $user_uid = arg(1);
    if (!isset($user_uid)) $user_uid = $user->uid;
    
    $settings = array(
      'show_user' => FALSE,
    );
    $header = userpoints_get_transaction_header($settings);
    //$query = db_select('userpoints_txn', 'p')->extend('PagerDefault')->extend('TableSort')
    $query = db_select('userpoints_txn', 'p')->extend('TableSort')
        ->fields('p')
        ->condition('p.uid', $user_uid)
        ->condition('p.status', '0') // only show approved userpoints
        ->orderByHeader($header)
        ->orderBy('p.txn_id', 'DESC');
        //->limit(variable_get(USERPOINTS_REPORT_LIMIT, 10));

    if (module_exists('taxonomy')) {
      $query->leftJoin('taxonomy_term_data', 't', 'p.tid = t.tid');
    }
    foreach ($query->execute() as $transaction) {
      $rows[] = userpoints_get_transaction_row($transaction, $settings);
    }
    
    $content['header'] = $header;
    $content['rows'] = $rows;
    return theme('userpoints_list_transaction', array('content' => $content));
}

// Override Hook User View from Userpoints Module
function userpoints_sepulsa_user_view_alter(&$build) {
    //drupal_set_message("<pre>".print_r($build, true)."</pre>");
    global $user;
    $amount = userpoints_get_current_points($user->uid);
    $amount = number_format($amount,0,",",".");
    $build['userpoints']['title']['#markup'] = "";
    $build['userpoints']['actions']['#links'] = [];
    $build['userpoints']['list']['#items'][0] = "Sepulsa Kredit: Rp. ".$amount;
}