<?php
/**
 * @file
 * campaign_tracker.module
 */

define('UTM_SOURCE_COOKIE', 'utm_source_cookie');
define('UTM_MEDIUM_COOKIE', 'utm_medium_cookie');
define('UTM_CAMPAIGN_COOKIE', 'utm_campaign_cookie');
variable_set('cookie_lifetime', 2592000); // 1 week

/* implement hook_boot */
function campaign_tracker_boot() {
  $cookie_lifetime = variable_get('cookie_lifetime', 2592000);
  //set cookie

  if (isset($_GET['utm_source'])) {
    setcookie(UTM_SOURCE_COOKIE, check_plain($_GET['utm_source']), time() + $cookie_lifetime, '/');
  }

  if (isset($_GET['utm_medium'])) {
    setcookie(UTM_MEDIUM_COOKIE, check_plain($_GET['utm_medium']), time() + $cookie_lifetime, '/');
  }

  if (isset($_GET['utm_campaign'])) {
    setcookie(UTM_CAMPAIGN_COOKIE, check_plain($_GET['utm_campaign']), time() + $cookie_lifetime, '/');
  }
}

/* implement hook_user_presave() */
function campaign_tracker_user_presave(&$edit, $account, $category) {
  $cookie_lifetime = variable_get('cookie_lifetime', 2592000);

  if (isset($_COOKIE[UTM_SOURCE_COOKIE])) {
    $edit['field_reg_utm_source'][LANGUAGE_NONE][0]['value'] = $_COOKIE[UTM_SOURCE_COOKIE];
    // remove cookie
    //setcookie(UTM_SOURCE_COOKIE, '', time() + $cookie_lifetime, '/');
  } else {
    $edit['field_reg_utm_source'][LANGUAGE_NONE][0]['value'] = 'direct';
  }
  if (isset($_COOKIE[UTM_MEDIUM_COOKIE])) {
    $edit['field_reg_utm_medium'][LANGUAGE_NONE][0]['value'] = $_COOKIE[UTM_MEDIUM_COOKIE];
    // remove cookie
    //setcookie(UTM_MEDIUM_COOKIE, '', time() + $cookie_lifetime, '/');
  }
  if (isset($_COOKIE[UTM_CAMPAIGN_COOKIE])) {
    $edit['field_reg_utm_campaign'][LANGUAGE_NONE][0]['value'] = $_COOKIE[UTM_CAMPAIGN_COOKIE];
    // remove cookie
    //setcookie(UTM_CAMPAIGN_COOKIE, '', time() + $cookie_lifetime, '/');
  }
}

/* implement hook_commerce_order_presave() */
function campaign_tracker_commerce_order_presave($order) {
  $cookie_lifetime = variable_get('cookie_lifetime', 2592000);

  if (isset($_COOKIE[UTM_SOURCE_COOKIE])) {
    $order->field_utm_source[LANGUAGE_NONE][0]['value'] = $_COOKIE[UTM_SOURCE_COOKIE];
    // remove cookie
    //setcookie(UTM_SOURCE_COOKIE, '', time() + $cookie_lifetime, '/');
  } else {
    $edit->field_utm_source[LANGUAGE_NONE][0]['value'] = 'direct';
  }
  if (isset($_COOKIE[UTM_MEDIUM_COOKIE])) {
    $order->field_utm_medium[LANGUAGE_NONE][0]['value'] = $_COOKIE[UTM_MEDIUM_COOKIE];
    // remove cookie
    //setcookie(UTM_MEDIUM_COOKIE, '', time() + $cookie_lifetime, '/');
  }
  if (isset($_COOKIE[UTM_CAMPAIGN_COOKIE])) {
    $order->field_utm_campaign[LANGUAGE_NONE][0]['value'] = $_COOKIE[UTM_CAMPAIGN_COOKIE];
    // remove cookie
    //setcookie(UTM_CAMPAIGN_COOKIE, '', time() + $cookie_lifetime, '/');
  }
}

function campaign_tracker_form_alter(&$form, $form_state, $form_id) {
  global $user;
  // Check if the user has the 'administrator' role.
  if (!in_array('administrator', $user->roles)) {
    $arg1 = arg(1);
    if (arg(0) == 'user' && isset($arg1) && arg(2) == 'edit') {
      $form['field_reg_utm_source']['#access'] = FALSE;
      $form['field_reg_utm_medium']['#access'] = FALSE;
      $form['field_reg_utm_campaign']['#access'] = FALSE;
    }
    if ($form_id == 'user_register_form') {
      $form['field_reg_utm_source']['#access'] = FALSE;
      $form['field_reg_utm_medium']['#access'] = FALSE;
      $form['field_reg_utm_campaign']['#access'] = FALSE;
    }
  }
}
