<?php
/**
 * @file
 * mobile_banner_install.module
 */

/**
 * Hook Implementations.
 */

/**
 * Implements hook_block_info().
 */
function mobile_banner_install_block_info() {
  $blocks = array();
  $blocks['mobile_banner_install'] = array(
    'info' => t('Mobile Banner Install'),
  );
  
  return $blocks;
}

/**
 * Implements hook_block_configure().
 */
function mobile_banner_install_block_configure($delta='') {
  $form = array();
  
  switch($delta) {
    case 'mobile_banner_install' :
     $form['logo'] = array(
	  '#name' => 'logo',
	  '#type' => 'managed_file',
	  '#title' => t('Choose an Image File'),
	  '#description' => t('Select an Image for the custom block.  Only *.gif, *.png, *.jpg, and *.jpeg images allowed.'),
	  '#default_value' => variable_get('logo_fid', ''),
	  '#upload_location' => 'public://',
	  '#upload_validators' => array(
		'file_validate_extensions' => array('gif png jpg jpeg'),
	  ),
	);

      break;
  }
  return $form;
}

/**
 * Implements hook_block_save().
 */
function mobile_banner_install_block_save($delta = '', $edit = array()) {
  switch($delta) {
    case 'mobile_banner_install' :
      // Saving the file, setting it to a permanent state, setting a FID variable
      $file = file_load($edit['logo']);
      $file->status = FILE_STATUS_PERMANENT;
      file_save($file);
      $block = block_load('mobile_banner_install', $delta);
      file_usage_add($file, 'mobile_banner_install', 'block', $block->bid);
      variable_set('logo_fid', $file->fid);
      break;
  }
}

/**
 * Implements hook_block_view().
 */
function mobile_banner_install_block_view($delta='') {
  $block = array();
  
  switch($delta) {
    case 'mobile_banner_install' :
      $block['content'] = mobile_banner_install_view();
      break;
  }
  
  return $block;
}

/**
 * Custom function to assemble renderable array for block content.
 * Returns a renderable array with the block content.
 * @return
 *   returns a renderable array of block content.
 */
function mobile_banner_install_view() {
  global $base_url;
  $content = array();
  $path = drupal_get_path('module', 'mobile_banner_install');

  if (empty($_COOKIE["mobile_banner_install_cookie"])) {
	$image_file = file_load(variable_get('logo_fid', ''));
	$image_path = '';

	if (isset($image_file->filename)) {
	  $image_path = $base_url.'/sites/default/files/'.$image_file->filename;
	}
	$cookie_lifetime = 30;
	//setcookie("mobile_banner_install_cookie", "1", time() + $cookie_lifetime, '/');
	$user_agent = $_SERVER['HTTP_USER_AGENT'];
	//drupal_set_message($user_agent);
	if(stripos($user_agent, 'android') !== false) {
	  $content['apps_path'] = "https://play.google.com/store/apps/details?id=com.sepulsa.android";
	  $content['image_path'] = $image_path;
	} else if (stripos($user_agent, 'iphone') !== false) {
	  $content['apps_path'] = "https://itunes.apple.com/us/app/sepulsa/id991045758?ls=1&mt=8";
	  $content['image_path'] = $image_path;
	}
  }
  
  //if (!empty($content))
	return theme('mobile_banner_install', array('content' => $content));
}

/**
 * Implements hook_theme().
 */
function mobile_banner_install_theme($existing, $type, $theme, $path) {
    return array(
      'mobile_banner_install' => array(
        'variables' => array('content' => NULL),
        'template' => 'mobile_banner_install', // place you file in 'theme' folder of you module folder
        'path' => drupal_get_path('module', 'mobile_banner_install')
      )
    );
}

