<?php
/**
 * @file
 * mobile_banner_install.module
 */

/**
 * Hook Implementations.
 */

/**
 * Implements hook_block_info().
 */
function mobile_banner_install_block_info() {
  $blocks = array();
  $blocks['mobile_banner_install'] = array(
    'info' => t('Mobile Banner Install'),
  );
  
  return $blocks;
}

/**
 * Implements hook_block_configure().
 */
function mobile_banner_install_block_configure($delta='') {
  $form = array();
  
  switch($delta) {
    case 'mobile_banner_install' :
      $form['home_about_title'] = array(
        '#type' => 'text_format',
        '#title' => t('Home About Title'),
        '#default_value' => variable_get('home_about_title', ''),
      );
        
      $form['home_about_text'] = array(
        '#type' => 'text_format',
        '#title' => t('Home About Text'),
        '#default_value' => variable_get('home_about_text', ''),
      );

      break;
  }
  return $form;
}

/**
 * Implements hook_block_save().
 */
function mobile_banner_install_block_save($delta = '', $edit = array()) {
  switch($delta) {
    case 'home_about' :
      // Saving the WYSIWYG text      
      variable_set('home_about_title', $edit['home_about_title']['value']);
      variable_set('home_about_text', $edit['home_about_text']['value']);
      break;
  }
}

/**
 * Implements hook_block_view().
 */
function mobile_banner_install_block_view($delta='') {
  $block = array();
  
  switch($delta) {
    case 'mobile_banner_install' :
      $block['content'] = mobile_banner_install_view();
      break;
  }
  
  return $block;
}

/**
 * Custom function to assemble renderable array for block content.
 * Returns a renderable array with the block content.
 * @return
 *   returns a renderable array of block content.
 */
function mobile_banner_install_view() {
    $block = array();
    
	$user_agent = $_SERVER['HTTP_USER_AGENT'];
	drupal_set_message($user_agent);
	//print strpos($user_agent); exit;
    $merchants = views_get_view_result('merchant', 'page');
    $content['home_about_title'] = variable_get('home_about_title', '');
    $content['home_about_text'] = variable_get('home_about_text', '');
    $content['merchants'] = $merchants;
    return theme('home_about_detail', array('content' => $content));
}

/**
 * Implements hook_theme().
 */
function mobile_banner_install_theme($existing, $type, $theme, $path) {
    return array(
      'mobile_banner_install' => array(
        'variables' => array('content' => NULL),
        'template' => 'mobile_banner_install', // place you file in 'theme' folder of you module folder
        'path' => drupal_get_path('module', 'mobile_banner_install')
      )
    );
}

