<?php
/**
 * @file
 * module file
 *
 * @category module
 * @package   WebEngage
 * @link     http://www.webengage.com/
 */

  define('WEBENGAGE_MODULE_PATH', drupal_get_path('module', 'webengage'));

 /**
  * Implements hook_permission().
  */
function webengage_permission() {
  return array('access webengage', 'create webengage', 'administer webengage');
}

 /**
  * Implements hook_menu().
  */
function webengage_menu() {
  $items["admin/webengage/action/main"] = array(
    'title' => 'WebEngage Settings',
    'description' => 'This is WebEngage Settings page',
    'page callback' => 'webengage_do_action_main',
    'access arguments' => array('admin_only'),
    'menu_name'        => 'webengage',
    'file'        => 'webengage_main.php',
    'type'             => MENU_NORMAL_ITEM,
  );

  $items["admin/webengage/action/callback"] = array(
    'title' => 'WebEngage Settings',
    'description' => 'This is WebEngage Settings page',
    'page callback' => 'webengage_do_action_callback',
    'access arguments' => array('admin_only'),
    'file'        => 'webengage_callback.php',
    'type' => MENU_CALLBACK,
  );

  return $items;
}

 /**
  * Implements hook_theme().
  */
function webengage_theme($existing, $type, $theme, $path) {
  module_load_include("php", "webengage", "webengage_main");
  module_load_include("php", "webengage", "webengage_callback");

  return array(
    'webengage_main' => array(
      'template' => 'webengage_main',
      'variables' => array(),
    ),
    'webengage_callback' => array(
      'template' => 'webengage_callback',
      'variables' => array(),
    ),
  );
}

/**
 * Implements hook_preprocess_page().
 */
function webengage_preprocess_page(&$vars, $hook) {
  drupal_add_css(drupal_get_path('module', 'webengage') . '/css/main.css', array(
    'group' => CSS_DEFAULT,
    'type' => 'file',
    'every_page' => TRUE));
  $vars['styles'] = drupal_get_css();
}

/**
 * Returns the form array.
 *
 * @param array $form
 *   The form array
 * @param array $form_state
 *   The form_state array
 *
 * @return array
 *   The filled form array
 */
function webengage_form_save_license_code($form, $form_state) {
  module_load_include("php", "webengage", "helper");
  $form['webengage_license_code'] = array(
    '#type' => 'textfield',
    '#title' => t("License Code"),
    '#required' => TRUE,
    '#default_value' => isset($form_state['values']['webengage_license_code']) ? $form_state['values']['webengage_license_code'] : webengageGetLicenseCode(),
  );

  $form['weAction'] = array(
    '#type' => 'hidden',
    '#value' => 'wp-save',
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Update License Code'),
  );

  return $form;
}

/**
 * Handles the form submit.
 *
 * @param array $form
 *   The form array
 * @param array $form_state
 *   The form_state array
 */
function webengage_form_save_license_code_submit($form, &$form_state) {
  module_load_include("php", "webengage", "helper");
  global $base_root;
  $redirect_url = "";
  $main_url = $base_root . base_path() . '?q=admin/webengage/action/main&noheader=true';

  if (webengageSetLicenseCode($form_state['values']['webengage_license_code']) == NULL) {
    $redirect_url = $main_url . '&' . 'error-message' . "=" . urlencode(t('Error in saving license code.'));
  }
  else {
    $redirect_url = $main_url . '&' . 'message' . "=" . urlencode(t('Your WebEngage widget license code has been updated.'));
  }

  drupal_goto($redirect_url);
}


/**
 * Implements hook_block_info().
 */
function webengage_block_info() {
  $blocks = array();
  $blocks['webengage'] = array(
    'info' => t('WebEngage Script'),
  );

  return $blocks;
}

 /**
  * Implements hook_block_view().
  */
function webengage_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'webengage':
      if ((arg(0) != 'admin')) {
        module_load_include("php", "webengage", "helper");
        $license_code = webengageGetLicenseCode();
        $widget_status = webengageGetWidgetStatus();
        if (strlen($license_code) > 0 && $widget_status == 'ACTIVE') {
          $block['content'] = webengage_get_webengage_script($license_code);
        }
      }
      break;
  }
  return $block;
}
