<?php

/**
 * Implements hook_services_resources().
 */
function apps_services_v2_services_services_resources() {
    return array(
        'services_v2' => array(
            'actions' => array(
                'sepulsa' => array(
                    'help' => 'List all sepulsa operator data',
                    'callback' => 'apps_services_v2_services_sepulsa_operator_list',
                    'file' => array(
                        'type' => 'inc',
                        'module' => 'apps_services_v2_services',
                        'name' => 'apps_services_v2_services',
                    ),
                    'documentation callback' => 'apps_services_v2_services_sepulsa_operator_list_doc',
                    'access callback' => 'services_access_menu',
                    'args' => array(
                      array(
                        'name' => 'source',
                        'type' => 'string',
                        'description' => 'the source of the request',
                        'source' => array(
                          'data' => 'source',
                          'param' => 'source',
                        ),
                        'optional' => FALSE,
                        'http_method' => 'POST',
                      ),
                    ),
                ),
            ),
        ),
    );
}

/**
 * Function apps_services_v2_services_sepulsa_operator_list_doc().
 *
 * Documentation callback for sepulsa operator list.
 */
function apps_services_v2_services_sepulsa_operator_list_doc() {
  global $base_url;
  $response = '
    {
      "source": "android"
    }
  ';
  $element = array(
    '#name' => 'Sepulsa Get Operator List',
    '#description' => 'Get Operator and Prefix Data from Sepulsa.',
    '#auth' => FALSE,
    '#path' => 'services_v2/sepulsa',
    // Example request. E.g., a request URL, headers, and a JSON array.
    '#request_url' => $base_url . '/air/services_v2/sepulsa.json',
    // Example response. E.g., a JSON array.
    '#response' => $response,
    // Resource prefix.
    // Errors.
    '#errors' => array(
	  'missing_argument' => array(
        '#question' => '401 Unauthorized : Missing required argument',
        '#description' => 'When drupal detect that the user missed some of the input required.',
        '#response' => '
        [
          "Missing required argument"
        ]',
      ),
      'internal_server' => array(
        '#question' => '500 Internal Server Error',
        '#description' => 'Drupal server can not handle the request. Drupal will output nothing.',
        '#response' => '',
      ),
    ),
  );
  return $element;
}