<?php
/**
 * @file
 * bank_transfer_notification_queue.module
 */


function bank_transfer_notification_queue_menu() {
    $items['bank_transfer_notification_queue'] = array(
      'title'            => t('Android Activation'),
      'description'      => t('Android Activation'),
      'page callback'    => 'bank_transfer_notification_queue',
      'access arguments' => array('administer site configuration'),
      'type'             => MENU_CALLBACK,
    );
    return $items;
}

function bank_transfer_notification_queue_cron() {
    $queue = DrupalQueue::get('queue_bank_transfer_notification');
    
    // GET last 2 hours bank transfer pending order AND not in notification queue table
    $query = "SELECT a.order_id, b.amount, a.mail FROM commerce_order a
            INNER JOIN commerce_payment_transaction b ON a.order_id = b.order_id
            LEFT OUTER JOIN bank_transfer_notification_queue c ON a.order_id = c.order_id
            WHERE
            a.status = 'pending'
            AND b.payment_method = 'bank_transfer'
            AND from_unixtime(a.created) > NOW() - INTERVAL 2 HOUR
            AND c.id is null";
    $result = db_query($query);
    foreach ($result as $row) {
        $queue_item = array('order_id' => $row->order_id, 'email' => $row->mail, 'amount' => $row->amount);
        $queue->createItem($queue_item);
    }
}

/**
 * Implements hook_cron_queue_info().
 */
function bank_transfer_notification_queue_cron_queue_info() {
    $queues = array();
    $queues['queue_bank_transfer_notification'] = array(
      'worker callback' => 'send_notification_email_queue', //function to send notification email
      'time' => 60, //seconds to spend working on the queue
    );
    return $queues;
}

function send_notification_email_queue($item) {
    // send notification email
    
    // update queue notification table    
    $exist_order_id = db_query_range("SELECT order_id FROM {bank_transfer_notification_queue} WHERE order_id = :order_id", 0, 1, array('order_id' => $item['order_id']))->fetchField(); 
    if ($exist_order_id == null) {
        $sent = send_notification_email($item['order_id'], $item['amount'], $item['email']);
        if ($sent) {
            db_query("INSERT INTO bank_transfer_notification_queue (order_id, status) VALUES ('".$item['order_id']."', 1)");
        }
    }
    watchdog('test drupal queue cron', '<pre>'.print_r($item, true).'</pre>');
}

// HOOK MAIL
function bank_transfer_notification_queue_mail($key, &$message, $params) {
    $message['subject'] = $params['subject'];
    $message['body'] = $params['body'];
    
    $headers = array(
        'MIME-Version' => '1.0',
        'Content-Type' => 'text/html;charset=iso-8859-1',
        'X-Mailer' => 'Drupal'
      );
    
    foreach ($headers as $key => $value) {
        $message['headers'][$key] = $value;
      }
}

function send_notification_email($order_id, $amount, $email){
    //$time = date('d/m/y H:i:s', '1429880400');
    //$test = strtotime('24-04-2015 17:00:00');
    //print $test; exit;
    $payment = commerce_payment_method_instance_load('bank_transfer|commerce_payment_bank_transfer');
    //print "<pre>".print_r($payment['settings'], true)."</pre>";
    // send email
    //$order_id = '1123';
    //$amount = '123';
    $to = $email;
    $subject = "Order ".$order_id." at Sepulsa Belum Dibayar";
    $message = '
        <table width="600" cellspacing="0" cellpadding="20" border="0" style="margin:auto;border:1px solid #dddddd">
            <tr><td valign="top" align="center" style="background-color:#f4f4f4">
                <table width="100%" cellspacing="0" cellpadding="20" border="0" style="font-family:open sans,helvetica,arial,sans-serif;font-size:14px;line-height:20px;color:#606060">
                  <tr><td valign="top" align="center">
                    <table cellspacing="0" cellpadding="0" border="0">
                    <tr>
                      <td align="left">
                        <a href="#14ce464c30a17991_14ce09e594ea3ad0_"><img width="200" alt="" src="https://www.sepulsa.com/sites/all/themes/sepulsa/images/logo.png" class="CToWUd"></a>
                      </td>
                      <td align="right">
                        <table width="200" cellspacing="5" cellpadding="0"><tbody><tr><td width="25" valign="middle" align="right"><a target="_blank" href="https://www.facebook.com/sepulsa"><img width="24px" alt="" src="https://www.sepulsa.com/sites/all/themes/sepulsa/images/icon-facebook.png" class="CToWUd"></a></td>
                        <td width="25" valign="middle" align="right"><a target="_blank" href="https://twitter.com/sepulsa_id"><img width="24px" alt="" src="https://www.sepulsa.com/sites/all/themes/sepulsa/images/icon-twitter.png" class="CToWUd"></a></td>
                        <td width="25" valign="middle" align="right"><a target="_blank" href="https://www.sepulsa.com/"><img width="24px" alt="" src="https://www.sepulsa.com/sites/all/themes/sepulsa/images/icon-link.png" class="CToWUd"></a></td>
                        <td width="25" valign="middle" align="right"><a target="_blank" href="mailto:info@sepulsa.com"><img width="24px" alt="" src="https://www.sepulsa.com/sites/all/themes/sepulsa/images/icon-mail.png" class="CToWUd"></a></td>
                        </tr></tbody></table>
                    </td></tr>
                    </table>

                  </td></tr>
                </table>
            </td></tr>
            
            <tr><td valign="top" align="center">
                <table width="100%" cellspacing="0" cellpadding="20" border="0" style="font-family:open sans,helvetica,arial,sans-serif;font-size:14px;line-height:20px;color:#606060">
                  <tr><td valign="top" align="center">
                    <table cellspacing="0" cellpadding="0" border="0">
                    <tr><td>
                        <p>Nomor transaksi '.$order_id.' anda sebesar Rp. '.$amount.' belum dibayar. Segera lakukan transfer sebelum order anda dibayarkan</p>
                        <h4 style="margin-top:0;margin-bottom:15px;font-size:16px">Info cara transfer</h4>
                        <p>
                          Nama Bank : <strong>'.$payment['settings']['details']['account_bank'].'</strong><br>
                          Nomor rekening : <strong>'.$payment['settings']['details']['account_number'].'</strong><br>
                          Atas nama : <strong>'.$payment['settings']['details']['account_owner'].'</strong><br>
                          Kantor cabang : '.$payment['settings']['details']['account_branch'].'
                        </p>
                        '.$payment['settings']['policy'].'
                        <p>
                          <strong>Keterangan transfer : Sepulsa Order 3502</strong><br>
                          Selalu masukkan keterangan transfer diatas ketika melakukan transfer. Hal ini untuk memudahkan proses pembayaran kamu dikonfirmasi dengan cepat.
                        </p>
                        <p>&nbsp;</p>
                        <p><span>Silahkan hubungi kami di <a target="_blank" style="color:#dc2c27;text-decoration:none;font-weight:bold" href="mailto:info@sepulsa.com">info@sepulsa.com</a> jika anda ada pertanyaan lebih lanjut mengenai pesanan anda.</span></p>
                    </td></tr>
                    </table>

                  </td></tr>
                </table>
            </td></tr>
            
            <tr><td valign="top" align="center">
            <table width="100%" cellspacing="0" cellpadding="20" border="0"><tbody><tr><td valign="top" align="center">
            <div style="border-top:1px solid #ddd;width:100%;display:block;min-height:1px;margin-top:15px;margin-bottom:15px"></div>
            <table width="150px" cellspacing="0" cellpadding="5"><tbody><tr><td width="25" valign="top" align="center"><a target="_blank" href="https://www.facebook.com/sepulsa"><img width="24px" alt="" src="https://www.sepulsa.com/sites/all/themes/sepulsa/images/icon-facebook.png" class="CToWUd"></a></td>
            <td width="25" valign="top" align="center"><a target="_blank" href="https://twitter.com/sepulsa_id"><img width="24px" alt="" src="https://www.sepulsa.com/sites/all/themes/sepulsa/images/icon-twitter.png" class="CToWUd"></a></td>
            <td width="25" valign="top" align="center"><a target="_blank" href="https://www.sepulsa.com/"><img width="24px" alt="" src="https://www.sepulsa.com/sites/all/themes/sepulsa/images/icon-link.png" class="CToWUd"></a></td>
            <td width="25" valign="top" align="center"><a target="_blank" href="mailto:info@sepulsa.com"><img width="24px" alt="" src="https://www.sepulsa.com/sites/all/themes/sepulsa/images/icon-mail.png" class="CToWUd"></a></td>
            </tr></tbody></table><table cellspacing="0" cellpadding="0"><tbody><tr><td height="10"></td>
            </tr><tr><td>
                              <span style="font-family:open sans,helvetica,arial,sans-serif;font-size:12px;line-height:1em;color:#606060">PT. Sepulsa Indonesia &copy; 2015, All Right Reserved.</span>
                            </td>
            </tr></tbody></table></td>
            </tr></tbody></table></td>
            </tr>

        </table>
            ';	
    $headers = "MIME-Version: 1.0" . "\r\n";
    $headers .= "Content-type:text/html;charset=iso-8859-1" . "\r\n";
    $headers .= "From: <info@sepulsa.com>" . "\r\n";

    $sent_email = mail($to,$subject,$message,$headers);
    if ($sent_email) return true;
    else return false;
}

function bank_transfer_notification_queue_uninstall() {
  drupal_uninstall_schema('bank_transfer_notification_queue');
}
