<?php
/**
 * @file
 * bank_transfer_notification_queue.module
 */


function bank_transfer_notification_queue_menu() {
    $items['bank_transfer_notification_queue'] = array(
      'title'            => t('Android Activation'),
      'description'      => t('Android Activation'),
      'page callback'    => 'bank_transfer_notification_queue',
      'access arguments' => array('administer site configuration'),
      'type'             => MENU_CALLBACK,
    );
	
    $items['admin/commerce/config/bank_transfer_notification_queue'] = array(
      'title'            => t('Bank Transfer Notification Setting'),
      'description'      => t('Bank Transfer Notification Setting'),
      'page callback'    => 'drupal_get_form',
      'page arguments'   => array('bank_transfer_notification_queue_setting'),
      'access arguments' => array('administer site configuration'),
      'type'             => MENU_NORMAL_ITEM,
    );
	
    return $items;
}

function bank_transfer_notification_queue(){
    //$test = strtotime('30-04-2015 10:30:00');
    //$time = date('d/m/y H:i:s', $test);
    //print $test."<br />".$time;
}

function bank_transfer_notification_queue_setting() {
    $form['bank_transfer_notification_queue_setting'] = array(
      //'#type' => 'text_format',
      '#type' => 'textarea',
      '#title' => t('Bank Transfer Notification Setting'),
      '#default_value' => variable_get('bank_transfer_notification_queue_setting', ''),
      '#description' => t('Bank Transfer Notification Setting'),
	  //'#format' => 'filtered_html',
    );

    return system_settings_form($form);
}

function bank_transfer_notification_queue_cron() {
    $queue = DrupalQueue::get('queue_bank_transfer_notification');
    
    // GET last 2 hours bank transfer pending order AND not in notification queue table
    $query = "SELECT a.order_id, b.amount, a.mail FROM commerce_order a
            INNER JOIN commerce_payment_transaction b ON a.order_id = b.order_id
            LEFT OUTER JOIN bank_transfer_notification_queue c ON a.order_id = c.order_id
            WHERE
            (a.status = 'pending' || a.status = 'processing') 
            AND b.payment_method = 'bank_transfer' 
            AND from_unixtime(a.created) + INTERVAL 2 HOUR < NOW() 
            AND c.id is null";
    $result = db_query($query);
    foreach ($result as $row) {
        $queue_item = array('order_id' => $row->order_id, 'email' => $row->mail, 'amount' => $row->amount);
        $queue->createItem($queue_item);
    }
}

/**
 * Implements hook_cron_queue_info().
 */
function bank_transfer_notification_queue_cron_queue_info() {
    $queues = array();
    $queues['queue_bank_transfer_notification'] = array(
      'worker callback' => 'send_notification_email_queue', //function to send notification email
      'time' => 60, //seconds to spend working on the queue
    );
    return $queues;
}

function send_notification_email_queue($item) {
    // send notification email
    
    // update queue notification table    
    $exist_order_id = db_query_range("SELECT order_id FROM {bank_transfer_notification_queue} WHERE order_id = :order_id", 0, 1, array('order_id' => $item['order_id']))->fetchField(); 
    if ($exist_order_id == null) {
        $sent = send_notification_email($item['order_id'], $item['amount'], $item['email']);
        if ($sent) {
            db_query("INSERT INTO bank_transfer_notification_queue (order_id, status) VALUES ('".$item['order_id']."', 1)");
            watchdog('bank_transfer_email_reminder', 'Email Successfully Sent <br /><pre>'.print_r($item, true).'</pre>');
        }
    }
}

// HOOK MAIL
function bank_transfer_notification_queue_mail($key, &$message, $params) {
    $message['subject'] = $params['subject'];
    $message['body'] = $params['body'];
    
    $headers = array(
        'MIME-Version' => '1.0',
        'Content-Type' => 'text/html;charset=iso-8859-1',
        'X-Mailer' => 'Drupal'
      );
    
    foreach ($headers as $key => $value) {
        $message['headers'][$key] = $value;
      }
}

function send_notification_email($order_id, $amount, $email){
    //$time = date('d/m/y H:i:s', '1429880400');
    //$test = strtotime('24-04-2015 17:00:00');
    //print $test; exit;
    $payment = commerce_payment_method_instance_load('bank_transfer|commerce_payment_bank_transfer');
	$bank_detail = '
	  <p>
		Nama Bank : <strong>'.$payment['settings']['details']['account_bank'].'</strong><br>
		Nomor rekening : <strong>'.$payment['settings']['details']['account_number'].'</strong><br>
		Atas nama : <strong>'.$payment['settings']['details']['account_owner'].'</strong><br>
		Kantor cabang : '.$payment['settings']['details']['account_branch'].'
	  </p>
	  '.$payment['settings']['policy'];
    $to = $email;
    $subject = "Order ".$order_id." di Sepulsa Belum Dibayar";
    $message = variable_get('bank_transfer_notification_queue_setting');
	$message = str_replace("[ORDERID]", $order_id, $message);
	$message = str_replace("[AMOUNT]", number_format($amount,0,",","."), $message);
	$message = str_replace("[BANK_DETAIL]", $bank_detail, $message);
	
    $headers = "MIME-Version: 1.0" . "\r\n";
    $headers .= "Content-type:text/html;charset=iso-8859-1" . "\r\n";
    $headers .= "From: <info@sepulsa.com>" . "\r\n";

    $sent_email = mail($to,$subject,$message,$headers);
    if ($sent_email) return true;
    else return false;
}

function bank_transfer_notification_queue_uninstall() {
  drupal_uninstall_schema('bank_transfer_notification_queue');
}
