<?php
/* implement hook_page_build() */
function mixpanel_sepulsa_page_build(&$page) {
  $item = menu_get_item();
  if (!path_is_admin($item['path'])) {
    if ($item['path'] == 'sepulsa') {
      drupal_add_js('mixpanel.track("Halaman Depan");', 'inline');
      drupal_add_js('jQuery("#edit-add-charge").click(function() {mixpanel.track("Langsung Bayar");});jQuery("#edit-add-cart").click(function() {mixpanel.track("Pilih Kupon");});', 'inline');
    }
    if ($item['path'] == 'coupon') {
      //drupal_add_js('mixpanel.track("Voucher");', 'inline');
      drupal_add_js('jQuery(".image-container a.image").click(function() {
        var title = jQuery(this).parent().parent().siblings().find("span").html();
        mixpanel.track("Voucher Click", {
          "title": title
        });
      });', array('type' => 'inline', 'scope' => 'footer'));
      drupal_add_js('jQuery(".post-content a.image").click(function() {
        var title = jQuery(this).parent().siblings().find("span").html();
        mixpanel.track("Voucher Click", {
          "title": title
        });
      });', array('type' => 'inline', 'scope' => 'footer'));
    }
  }
}