<?php
/**
 * @file
 * commerce_kredivo.module
 *
 * @author andre4s_y
 */

/**
 * Hook Implementations.
 */

/**
 * Implements hook_commerce_payment_method_info().
 */
function commerce_kredivo_commerce_payment_method_info() {
  $payment_methods = array();

  // @todo: check whether terminal is possible.
  $payment_methods['commerce_kredivo'] = array(
    'base' => 'commerce_kredivo',
    'title' => t('Kredivo Payment Gateway'),
    'short_title' => t('Kredivo'),
    'description' => t('Kredivo Payment Gateway Integration'),
    'terminal' => FALSE,
    'offsite' => TRUE,
    'offsite_autoredirect' => TRUE,
    'file' => 'commerce_kredivo.payment.inc',
  );

  return $payment_methods;
}

/**
 * Implements hook_menu().
 */
function commerce_kredivo_menu() {
  $items = array();

  // Define an always accessible path to receive push notification.
  $items['commerce_kredivo/notification/%commerce_order/%commerce_payment_transaction'] = array(
    'page callback' => 'commerce_kredivo_notification',
    'page arguments' => array(2, 3),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'file' => 'commerce_kredivo.notification.inc',
  );

  return $items;
}
