<?php
/**
 * @file
 * facebook_pixel.module
 *
 * Module for Facebook pixel
 */

/**
 * Implements hook_block_info().
 */
function facebook_pixel_block_info() {
  $blocks['facebook-pixel'] = array(
    'info' => t('Facebook Pixel'),
    'region' => 'content',
    'status' => 1,
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'pages' => 'checkout/*/complete',
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function facebook_pixel_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'facebook-pixel':
      $url = facebook_pixel_get_value();
      $block['content'] = array(
        '#attached' => array(
          'js' => array(
            'data' => drupal_add_js("jQuery(document).ready(function () { !function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
                          n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
                          n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;
                          t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,
                          document,'script','//connect.facebook.net/en_US/fbevents.js');

                          fbq('init', '" . variable_get('facebook_pixel_id', '1198972743465542') . "');
                          fbq('track', 'Purchase', {value: '" . $url['amount'] . "', currency:'" . $url['currency_code'] . "'}); });",
                          array('type' => 'inline', 'scope' => 'header')
            ),
          ),
        ),
      );
      break;
  }
  return $block;
}

/**
 * Function to get amount and currency code.
 */
function facebook_pixel_get_value() {
  $id = intval(arg(1));
  $var = commerce_order_load($id);
  drupal_set_message('<pre>'.print_r($var, true).'</pre>');
  watchdog('facebook_pixel', '<pre>'.print_r($var, true).'</pre>');
  $data['amount'] = $var->data['commerce_veritrans']['amount'];
  $data['currency_code'] = $var->data['commerce_veritrans']['currency_code'];
  return $data;
}

/**
 * Impelements hook_menu().
 */
function facebook_pixel_menu() {
  // Administration pages.
  $items['admin/config/system/facebook-pixel'] = array(
    'title' => 'Facebok Pixel Configuration',
    'description' => 'ID Facebook Pixel',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('facebook_pixel_form'),
    'access arguments' => array('access administration pages'),
  );
  return $items;
}

/**
 * Impelements hook_form().
 */
function facebook_pixel_form($form, &$form_state) {

  $form['facebook_pixel_id'] = array(
    '#type' => 'textfield',
    '#title' => 'ID Facebook Pixel ?',
    '#size' => 20,
    '#maxlength' => 20,
    '#default_value' => variable_get('facebook_pixel_id', '1198972743465542'),
    '#required' => TRUE,
  );

  return system_settings_form($form);
}
