<?php
/**
 * @file
 * sepulsa_adminui.module
 *
 * @author azul@sepulsa.com
 */

/**
 * Implements hook_menu().
 */
function sepulsa_adminui_menu() {
  // Create menu to handle several sepulsa admin tools.
  $items['admin/commerce/tools'] = array(
    'title' => 'Tools',
    'description' => 'Sepulsa Admin Tools.',
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('access administration pages'),
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function sepulsa_adminui_form_commerce_discount_form_alter(&$form, &$form_state, $form_id) {
  // Set Discount status default to: Disabled.
  $form['status']['#default_value'] = 0;
  // Disable product discount option.
  if (isset($form['commerce_discount_type']['#options']['product_discount'])) {
    unset($form['commerce_discount_type']['#options']['product_discount']);
  }
  // Disable product free option.
  if (isset($form['commerce_discount_fields']['commerce_discount_offer']['und']['form']['type']['#options']['free_products'])) {
    unset($form['commerce_discount_fields']['commerce_discount_offer']['und']['form']['type']['#options']['free_products']);
  }
  // Emphasize: name description.
  $form['component_title']['#required'] = TRUE;
  $form['component_title']['#description'] = '<span style="font-weight: bold; color: red;">' . t('Warning: this name will be shown to customers!') . '<span>';
}
