<?php

/**
 * @file
 */

/**
 * Implements hook_menu().
 */
function kraken_api_menu() {
  $items = array();
  $items['admin/config/services/kraken-api'] = array(
    'title' => 'Kraken API settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('kraken_api_settings'),
    'access arguments' => array('administer site configuration'),
    'file' => 'kraken_api.admin.inc',
  );

  $items['notification/kraken-api'] = array(
    'page callback' => 'kraken_api_notification_callback',
    'access callback' => TRUE,
    'file' => 'kraken_api.pages.inc',
  );

  return $items;
}

function kraken_api_products($field, $instance, $entity_type, $entity, $cacheable) {
  module_load_include('inc', 'kraken_api');
  $products_list = kraken_api_call('product');

  foreach ($products_list['list'] as $product) {
    $products[$product['product_id']] = "{$product['type']}: {$product['operator']} ({$product['nominal']})";
  }

  return $products;
}

/**
 * Implements hook_views_api().
 */
function kraken_api_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'kraken_api') . '/includes/views',
  );
}
