<?php
/**
 * @file
 * bank_transfer_notification.module
 */

/**
 * Impelements hook_menu().
 */
function bank_transfer_notification_menu() {
  $items = array();

  // Administration pages.
  $items['admin/config/system/bank-transfer-notification'] = array(
    'title' => 'Bank Transfer Notification',
    'description' => 'Configuration time to send email',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('bank_transfer_notification_form'),
    'access arguments' => array('access administration pages'),
  );

  return $items;
}

/**
 * Impelements hook_form().
 */
function bank_transfer_notification_form($form, &$form_state) {

  $form['bank_transfer_notification_hour'] = array(
    '#type' => 'textfield',
    '#title' => 'Notify user ... hour after order. *(max : 3 hour)',
    '#size' => 1,
    '#maxlength' => 1,
    '#default_value' => variable_get('bank_transfer_notification_hour', 2),
    '#required' => TRUE,
  );

  return system_settings_form($form);
}

/**
 * Implements hook_cron().
 */
function bank_transfer_notification_cron() {
  $queue = DrupalQueue::get('queue_bank_transfer_notification');
  $query = "SELECT a.order_id, b.amount, a.mail 
              FROM commerce_order a
            INNER JOIN commerce_payment_transaction b ON a.order_id = b.order_id
            LEFT OUTER JOIN bank_transfer_notification_queue c ON a.order_id = c.order_id
            WHERE (a.status = 'pending' || a.status = 'processing') 
              AND b.payment_method = 'bank_transfer' 
              AND from_unixtime(a.created) + INTERVAL " . variable_get('bank_transfer_notification_hour', 2) . " HOUR < NOW() 
              AND from_unixtime(a.created) > NOW() - INTERVAL 12 HOUR
              AND c.id is null";
  $result = db_query($query);
  foreach ($result as $row) {
    $order = commerce_order_load($row->order_id);
    if ($order->status == 'pending' || $order->status == 'processing') {
      $queue->createItem($order);
    }
  }
}

/**
 * Implements hook_cron_queue_info().
 */
function bank_transfer_notification_cron_queue_info() {
  $queues = array();
  $queues['queue_bank_transfer_notification'] = array(
    'worker callback' => 'bank_transfer_notification_send_email',
    'time' => 60,
  );
  return $queues;
}

/**
 * Function bank_transfer_notification_send_email().
 *
 * @todo
 * Send email to notification.
 * @param object $order
 * Object item commerce_order.
 */
function bank_transfer_notification_send_email($order) {
  // Make sure these orders have not received email notification.
  $exist_order_id = db_query_range("SELECT order_id FROM {bank_transfer_notification} WHERE order_id = :order_id", 0, 1, array('order_id' => $order->order_id))->fetchField();

  $user_order = user_load($order->uid);

  if (empty($exist_order_id)) {
    $payment = commerce_payment_method_instance_load($order->data['payment_method']);

    $lang = language_default('language');
    
    $send = drupal_mail(
      'bank_transfer_notification',
      'notif',
      $user_order->mail,
      $lang,
      array(
        'account_owner' => $payment['settings']['details']['account_owner'],
        'account_number' => $payment['settings']['details']['account_number'],
        'account_bank' => $payment['settings']['details']['account_bank'],
        'account_branch' => $payment['settings']['details']['account_branch'],
        'policy' => $payment['settings']['details']['policy'],
      )
    );

    if ($send) {
      db_insert('bank_transfer_notification')
      ->fields(array('order_id' => $order->order_id, 'status' => 1))
      ->execute();
      watchdog('bank_transfer_notification', t("Send Nofitication to !mail Success.",
        array('!mail' => $user_order->mail)));
    }
    else {
      watchdog('bank_transfer_notification', t("Send Nofitication to !mail Failed.",
        array('!mail' => $user_order->mail)));
    }

  }
}

/**
 * Implements hook_mail()
 */
function bank_transfer_notification_mail($key, &$message, $params) {
  switch ($key) {
    case 'notif':
      $langcode = $message['language'];
      $message['subject'] = t("Bank Transfer Notification from !site", 
                            array('!site' => variable_get('site_name')), 
                            array('langcode' => $langcode));
      $message['body'][] = variable_get('opening_bank_transfer_notification', 'Mohon lakukan pembayaran ke :');
      $message['body'][] = '';
      $message['body'][] = t("Nama Bank : !bank", 
        array('!bank' => $params['account_bank']), 
        array('langcode' => $langcode));
      $message['body'][] = t("Nomor rekening : !norek", 
        array('!norek' => $params['account_number']), 
        array('langcode' => $langcode));
      $message['body'][] = t("Atas nama : !account_owner", 
        array('!account_owner' => $params['account_owner']), 
        array('langcode' => $langcode));
      $message['body'][] = t("Kantor cabang : !account_branch", 
        array('!account_branch' => $params['account_branch']), 
        array('langcode' => $langcode));
      $message['body'][] = '';
      $message['body'][] = t("!policy", 
        array('!policy' => $params['policy']), 
        array('langcode' => $langcode));
      break;
  }
}
