<?php

/**
 * Implements hook_commerce_checkout_pane_info_alter().
 */
function sepulsa_checkout_commerce_checkout_pane_info_alter(&$checkout_panes) {
  $checkout_panes['checkout_completion_message']['callbacks']['settings_form'] = 'sepulsa_checkout_completion_message_pane_settings_form';
  $checkout_panes['checkout_completion_message']['callbacks']['checkout_form'] = 'sepulsa_checkout_completion_message_pane_checkout_form';
}

function sepulsa_checkout_completion_message_pane_settings_form($checkout_pane) {
  module_load_include('inc', 'commerce_checkout', '/includes/commerce_checkout.checkout_pane.inc');
  $form = commerce_checkout_completion_message_pane_settings_form($checkout_pane);
  $form['container']['commerce_checkout_completion_message'] = array(
    '#type' => 'value',
    '#value' => commerce_checkout_completion_message_default(),
    '#tree' => TRUE,
  );

  $message = variable_get('commerce_checkout_completion_message', commerce_checkout_completion_message_default());

  foreach (commerce_payment_methods() as $method_id => $payment_method) {
    $form['container']['commerce_checkout_completion_message'][$method_id] = array(
      '#type' => 'text_format',
      '#title' => t('Checkout completion message for %payment_method', array('%payment_method' => $payment_method['title'])),
      '#default_value' => isset($message[$method_id]) ? $message[$method_id]['value'] : NULL,
      '#format' => isset($message[$method_id]) ? $message[$method_id]['format'] : NULL,
    );
  }

  $form['container']['commerce_checkout_completion_message']['anonymous'] = array(
    '#type' => 'text_format',
    '#title' => t('Checkout completion message for anonymous user'),
    '#default_value' => isset($message['anonymous']) ? $message['anonymous']['value'] : NULL,
    '#format' => isset($message['anonymous']) ? $message['anonymous']['format'] : NULL,
  );
  $form['container']['commerce_checkout_completion_message']['authenticated'] = array(
    '#type' => 'text_format',
    '#title' => t('Checkout completion message for authenticated user'),
    '#default_value' => isset($message['authenticated']) ? $message['authenticated']['value'] : NULL,
    '#format' => isset($message['authenticated']) ? $message['authenticated']['format'] : NULL,
  );

  return $form;
}

function sepulsa_checkout_completion_message_pane_checkout_form($form, &$form_state, $checkout_pane, $order) {
  $pane_form = array();
  $markup = sepulsa_checkout_completion_message_message($order);
  $pane_form['message'] = array(
    '#markup' => $markup,
  );

  return $pane_form;
}

function sepulsa_checkout_completion_message_message($order, $format = NULL) {
  $role = user_is_logged_in() ? 'authenticated' : 'anonymous';
  $payment_method = commerce_payment_method_instance_load($order->data['payment_method']);
  $markup = '';

  // Load the completion message.
  $message = variable_get('commerce_checkout_completion_message', commerce_checkout_completion_message_default());

  foreach (array($payment_method['method_id'], $role) as $part) {
    // Perform translation.
    $message[$part]['value'] = commerce_i18n_string('commerce:checkout:complete:message', $message[$part]['value'], array('sanitize' => FALSE));

    // Perform token replacement.
    $message[$part]['value'] = token_replace($message[$part]['value'], array('commerce-order' => $order), array('clear' => TRUE));

    // Apply the proper text format.
    $message[$part]['value'] = check_markup($message[$part]['value'], empty($format) ? $message[$part]['format'] : $format);

    $markup .= $message[$part]['value'];
  }

  return $markup;
}
