<?php
/**
 * @file
 * sepulsa_report.module
 *
 * @author ananto@sepulsa.com
 */

/**
 * Hook Implementations.
 */

 /**
 * Implements hook_menu().
 */
function sepulsa_reports_menu() {
  $items = array();

  $items['admin/commerce/sepulsa_reports'] = array(
    'title' => 'Sepulsa Reports',
    'description' => 'View Sepulsa Reports.',
    'access arguments' => array('access sepulsa reports'), // Inherited by children.
    'page callback' => 'sepulsa_reports_dashboard',
    'file' => 'sepulsa_reports.dashboard.inc',
    'weight' => -30,
  );
  $items['admin/commerce/sepulsa_reports/dashboard'] = array(
    'title' => 'Dashboard',
    'description' => 'View Sepulsa Reports.',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => 0,
  );
  $items['admin/commerce/sepulsa_reports/sales'] = array(
    'title' => 'Sales',
    'description' => 'View Sales Reports.',
    'access arguments' => array('access sepulsa reports'),
    'page callback' => 'system_admin_menu_block_page',
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 0,
  );

  $items['admin/commerce/sepulsa_reports/voucher'] = array(
    'title' => 'Voucher Report',
    'description' => 'View voucher reports.',
    'access arguments' => array('access sepulsa reports'),
    'page callback' => 'sepulsa_reports_voucher_check',
    'file' => 'sepulsa_reports.voucher.inc',
  );

  $items['admin/commerce/sepulsa_reports/voucher/basic'] = array(
    'title' => 'Basic',
    'description' => 'View Sepulsa Reports.',
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );

  $items['admin/commerce/sepulsa_reports/voucher/live'] = array(
    'title' => 'Voucher Report Live',
    'description' => 'View live voucher reports.',
    'access arguments' => array('access sepulsa reports'),
    'page callback' => 'sepulsa_reports_live_voucher_check',
    'file' => 'sepulsa_reports.voucher.inc',
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function sepulsa_reports_permission() {
  return array(
    'access sepulsa reports' => array(
      'title' => t('Access sepulsa reports'),
    )
  );
}
